data_pipelines:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: useqqwp-th02887

      # User/password auth
      user: OMKAR2  
      password: P00l$ome

      role: 'dbt_role'
      database: 'dbt_db'
      warehouse: 'dbt_wh'
      schema: 'dbt_schema'
      threads: 1
      client_session_keep_alive: False
      query_tag: 'anything'

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false